version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "4443:${PORT:-443}/tcp"
      - "80:${REDIRECTION_PORT:-80}/tcp"
    volumes:
      - './nginx/templates/:/etc/nginx/templates'
      - './nginx/etc-ssl/private:/etc/ssl/private/${SERVER_NAME:-pi-hole.lan}'
      - './nginx/etc-ssl/public:/etc/ssl/certs/${SERVER_NAME:-pi-hole.lan}'
    restart: unless-stopped
    environment:
      - PORT=${PORT:-443}
      - REDIRECTION_PORT=${REDIRECTION_PORT:-80}
      - PRIVATE_KEY_NAME=${PRIVATE_KEY_NAME:-key.pem}
      - CERTIFICATE_NAME=${CERTIFICATE_NAME:-cert.pem}
      - SERVER_NAME=${SERVER_NAME:-pi-hole.lan}
  pihole:
    depends_on:
      - nginx
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
    # Volumes store your data between container upgrades
    volumes:
      - './pi-hole/etc-pihole/:/etc/pihole/'
      - './pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
